### ISSUE TITLE
clean up git config

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/prototyper#21]
At the moment, my commit log is "spammed" with `dist` and `typings`. Cannot rebase because of that (unless I push dist and typings).

Any objections if I try to clean that up?

**Comment by adriatic** [comment]
Go ahead Daniel, please.

**Comment by Thanood** [comment]
done in #20

**Comment by Thanood** [comment]
Can I also remove the calls to `gulp-notify`? 😄 
I can't stand the toasts complaining about kendo not being found (it is there).

**Comment by adriatic** [comment]
Yes, of course - these alerts are really violent. I inherited that from Moterey.

**Comment by Thanood** [comment]
done
