### ISSUE TITLE
repository got hosed

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/prototyper#30]
This morning, I found two PRs that I wanted to merge into master:

1. https://github.com/monterey-framework/prototyper/pull/29
2. https://github.com/monterey-framework/prototyper/pull/24

I did PR 1 without a hitch and trying to do PR 2 I was told that I need to fix two conflicts, which I did using GitHub's `web editor` (I find that piece a very useful addition).

As it turns out, I did the merge of PR 2 backwards (merger master into observer) - where I still do not know how did I manage that. 

At that time, trying to run `git pull` in my console - I got a massive amount of TS errors and immediately decided that the best way out of this mess would be to revert the PR 2 (`observer`), using GitHub desktop client - however, that would not work saying that I need to first resolve my local conflicts.

By now, I realized that I am sinking in that quick-sand, so I hid my local copy (renamed it) and created a local clone from @Thanood's repo. When I built this (went fine) trying `gulp watch` I got:

```
λ gulp watch
[11:44:14] Using gulpfile C:\work\monterey-framework\prototyper\gulpfile.js
[11:44:14] Starting 'build'...
[11:44:14] Starting 'clean'...
[11:44:14] Finished 'clean' after 13 ms
[11:44:15] Starting 'build-system'...
[11:44:15] Starting 'build-html'...
[11:44:15] Starting 'build-less'...
[11:44:15] Starting 'build-css'...
[11:44:15] Starting 'build-json'...
[11:44:15] Finished 'build-less' after 342 ms
app\src\app.ts(1,43): error TS2307: Cannot find module 'aurelia-router'.
app\src\blur-image.ts(1,26): error TS2307: Cannot find module 'aurelia-framework'.
app\src\main.ts(2,23): error TS2307: Cannot find module 'aurelia-framework'.
app\src\mpc\basic-components\collector-component.ts(7,28): error TS2304: Cannot find name 'kendo'.
app\src\mpc\basic-components\collector-component.ts(39,28): error TS2503: Cannot find namespace 'kendo'.
app\src\mpc\basic-components\mpc-component.ts(1,28): error TS2307: Cannot find module 'aurelia-framework'.
app\src\mpc\basic-components\package-chooser.ts(1,26): error TS2307: Cannot find module 'aurelia-framework'.
app\src\mpc\basic-components\package-chooser.ts(7,24): error TS2503: Cannot find namespace 'kendo'.
app\src\mpc\basic-components\package-chooser.ts(10,28): error TS2304: Cannot find name 'kendo'.
app\src\mpc\basic-components\version-chooser.ts(1,36): error TS2307: Cannot find module 'aurelia-framework'.
app\src\mpc\basic-components\version-chooser.ts(7,16): error TS2503: Cannot find namespace 'kendo'.
app\src\mpc\basic-components\version-chooser.ts(9,23): error TS2503: Cannot find namespace 'kendo'.
app\src\mpc\basic-components\version-chooser.ts(13,27): error TS2304: Cannot find name 'kendo'.
app\src\mpc\basic-components\version-chooser.ts(26,25): error TS2503: Cannot find namespace 'kendo'.
app\src\mpc\data\package-service.ts(1,34): error TS2307: Cannot find module 'aurelia-framework'.
app\src\mpc\data\package-service.ts(2,26): error TS2307: Cannot find module 'aurelia-fetch-client'.
[11:44:17] TypeScript: 16 semantic errors
[11:44:17] TypeScript: emit succeeded (with errors)
[11:44:17] Finished 'build-css' after 2.03 s
[11:44:17] Finished 'build-html' after 2.08 s
[11:44:17] Finished 'build-json' after 2.13 s
[11:44:17] Finished 'build-system' after 2.23 s
[11:44:17] Finished 'build' after 2.25 s
[11:44:17] Starting 'watch'...
[11:44:17] Finished 'watch' after 14 ms
[2017-01-02T16:44:17.264Z] [electron-connect] [server] started electron process: 9096
[2017-01-02T16:44:17.264Z] [electron-connect] [server] created and listening on 30080

[2017-01-02T16:44:17.910Z] [electron-connect] [server] client (window_id: 1) started.
[2017-01-02T16:44:17.912Z] [electron-connect] [client: 1] connected server
```

This app seems to run fine - which maybe explains why Daniel did not realize that his repo is "broken". Clearly, my merge of Daniel's PR (PR 1) above) may have easily caused some of my catastrophe here - but I really do not care nor does it make sense to resolve whether this is a true statement

### Summary

I see several options to move forward 

1. Revert my today's two merges (this would be ideal) - if someone can tell me how
2. Fix the 16 semantics errors in my clone of Daniel's repo and declare that to be the first version of "new prototyper" (this requires nuking of my original repo of course)
3. Fix my local sources (I have saved that of course) from Daniel's repo and sync it with (currently broken https://github.com/monterey-framework/prototyper).

Anyone with some good advice?

**Comment by adriatic** [comment]
Did not really expect anyone's help on hot to revert a faulty merge (not only that should not merged the observer branch, I also manager to merge master into observer ???). The actual process of reverting a merge is rather complex ()https://www.kernel.org/pub/software/scm/git/docs/howto/revert-a-faulty-merge.html) and the situation at hand is not worth spending  even much less effort - as I really do not care about this repo's history. 

___I will bail myself out - and am writing this to warn all of us, to be a lot more careful than I was this morning.___

**Comment by Thanood** [comment]
Sorry, I thought this was solved by Jeroen's hint regarding TS..
The easiest way would be to clone my repo into another folder, delete your `app/src/mpc` directory and copy my files from that folder over. Then upload to git.

**Comment by adriatic** [comment]
Thanks, Daniel - although you should not be reading this crap at this time 😏 

I fixed the situation with ease, using less complicated approach:

- took a clone of the original master
- added all missing typings (aurelia and kendo)
- fixed .gitignore to ensure that typings are are indeed saved.
- replaced the `collector-component.ts` and `screen.ts` with the same files from your repo (there are the only two affected by the `observer` PR, which I should not have merged.

I will push this to the master to make it usable for you again and then try to add some more code, despite the fact that I mucked with this so long that I am semi pissed at myself 😏
