### ISSUE TITLE
Why I do not see the data in the grid

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/prototyper#7]
The grid is the reference to [this](https://github.com/monterey-framework/prototyper/blob/master/app/src/mpc/components/version-chooser.html#L7) kendo grid - which is rendered as

![image](https://cloud.githubusercontent.com/assets/2712405/21408278/274583d6-c7a2-11e6-8543-0498f4908dd7.png)

The problem ought to be on [this line](https://github.com/monterey-framework/prototyper/blob/master/app/src/mpc/components/version-chooser.html#L10):

```
<ak-col k-title="Version" k-field="$dataItem"></ak-col>
```

where the `$dataItem` is just one of the many silly attempts I made to properly reference the data for this column.

What is the correct reference? I did not want to introduce the schema since this is just an array of strings.

**Comment by JeroenVinke** [comment]
http://www.telerik.com/forums/grid-support-for-data-in-array-form-instead-of-object-form#MeaaYTaq1kCVy0AwlhfEbA

**Comment by adriatic** [comment]
Did you know about this - or discovered it now? I would never expect such restriction as the same array of strings can be used as data for autocomplete control. However multi dimensional arrays make no sense in autocomplete, so my "analogy" does not apply.

**Comment by JeroenVinke** [comment]
> the DataSource component is designed to work with array of objects with named fields

I did not know about this, but we are not providing an array of objects with named fields

**Comment by JeroenVinke** [comment]
I cannot seem to find an example that uses an array of strings (with the grid control). Perhaps this question is better suited for the telerik folks?

**Comment by adriatic** [comment]
It's not worth looking into ways to go around the rule that grid data should be an array of objects. Even my convoluted example is a stretch (using a handmade array of version numbers); I did that for simplicity just to see how the GUI "feels like". Now, when I start getting real data from npm registry, I will never have to deal with arrays of strings alone.

**Comment by adriatic** [comment]
My next upgrade (not checked in Git):

- new definition of the versions array (which is now an array of objects)
 ```
	private versions : [
		{1, "3.2.1"},
		{2, "4.0.3"},
		{3, "4.1.0"},
		{4, "4.2.0"},
		{5, "4.3.0"},
		{6, "4.4.0"},
		{7, "4.5.0"},
		{8, "4.6.1"},
		{9, "4.6.3"},
		{10, "4.7.0"},
		{11, "4.7.1"},
		{12, "4.7.2"},
		{13, "4.7.3"},
		{14, "4.7.4"},
		{15, "4.7.5"},
		{16, "4.7.6"},
		{17, "4.7.7"},
		{18, "4.7.8"},
		{19, "4.7.9"},
		{20, "4.8.0"},
		{21, "4.7.1"},
		{22, "4.7.2"},
		{23, "4.7.3"},
		{24, "4.7.4"},
		{25, "4.7.5"},
		{26, "4.7.6"},
		{27, "4.7.7"},
		{28, "4.7.8"},
		{29, "4.7.9"},
		{30, "4.8.0"},
		{31, "4.8.1"},
		{32, "4.8.2"},
		{33, "4.8.3"},
		{34, "4.8.4"}
	]
```

- new definition of the constructor:
 ```
	constructor() {
		this.datasource = new kendo.data.DataSource({
			data: this.versions,
			schema: {
				model: {
					fields: {
						id: {type: 'number'},
						ver: {type: 'string'}
					}
				}
			},
	    	pageSize: 40			
		});
```

The rendering of this version is this:

![image](https://cloud.githubusercontent.com/assets/2712405/21445117/118f790c-c883-11e6-8439-33bb26b4a77a.png)

because the data is not defined:

![image](https://cloud.githubusercontent.com/assets/2712405/21445141/563ac778-c883-11e6-9425-7936aab8ed85.png)

My guess: the `versions` array of objects needs to be declared prior to being used in the constructor, but I am puzzled about why Typescript did not complain.

**Comment by JeroenVinke** [comment]
`private versions: [{ // etc`

Should be

`private versions = [{`

The `:` is the definition of the type of the versions variable, while `=` is the assignment of a value.

Also, the objects in the versions array need property names:

`private versions = [{ ver: '1.0.0' }, { ver: '1.2.0' }]`

The property names hete (ver) can be used in the grid (and can be defined in the datasource's model).

**Comment by adriatic** [comment]
After way too many "misunderstandings" (read: I should read documents a lot more carefully), here we are:

![image](https://cloud.githubusercontent.com/assets/2712405/21455930/32094c34-c8f2-11e6-93eb-db6691b5cb22.png)

Comments:
- the `:` . `=` swap is "normal" I understand the difference completely, but kepp failing to use the right symbol in the given context.
- the attempt to replace the array of strings with the array of objects wen astray, by trying to make the the array of objects with int and string attributes - an unnecessary complication, where I hoped that the definition of the schema will match that pair with "key" and "value"
