### ISSUE TITLE
How to create the checkbox in Kendo?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/prototyper#8]
![image](https://cloud.githubusercontent.com/assets/2712405/21487739/9c26a4c2-cb9f-11e6-9436-a2674848d73b.png)

I do not want to use something like http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid-inline-editing - as using the labelled button takes too much space and it feels too heavy.

There is a brief advice [here](http://www.telerik.com/forums/styling-html-checkbox-via-kendo-theme-please-provide-example) which points to [here](http://docs.telerik.com/kendo-ui/styles-and-layout/appearance-styling), but I have not found the `k-checkbox css class` item

Any ideas?

**Comment by JeroenVinke** [comment]
Something like https://gist.run/?id=44e1c8f61004f1068405059ca087df20 ?

**Comment by adriatic** [comment]
Precisely like that (did you create this as a service to me, or you already had it stashed somewhere?; this should be a catalog sample)

**Comment by JeroenVinke** [comment]
> Precisely like that (did you create this as a service to me, or you already had it stashed somewhere?; this should be a catalog sample)

No I made it for you (with the intent to possibly put it on the catalog site)

**Comment by adriatic** [comment]
I was looking for  **"checkbox"** type in  `<input type="checkbox" checked.two-way="Checked">` (still not sure where it is defined)
